# Usar Usuario, Clave y Base de Datos con su propia información, por ejemplo:
# USER: gonzalezj       --->>> su apellido más la primera letra de su nombre
# PASSWORD: Jesus556    --->>> una clave que ud. elija
# DB: Prueba            --->>> la Base de Datos deberá tener el nombre de Prueba 

version: '3.1'

services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD= root
      - MYSQL_DATABASE= Prueba
      - MYSQL_USER=fernandoL
      - MYSQL_PASSWORD=uzui
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    restart: always

volumes:
  mysql_data:
